services:
  - type: web
    name: fallguard
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 120 --workers 1 main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
